# Generated by Django 3.2.12 on 2022-06-13 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220613_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderquantity',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость заказа'),
        ),
    ]
