# Generated by Django 3.2.12 on 2022-06-13 14:57

from django.db import migrations
from django.db.models import Sum, F

def copy_cost_orders(apps, schema_editor):
    OrderQuantity = apps.get_model('foodcartapp', 'OrderQuantity')
    Order = apps.get_model('foodcartapp', 'Order')
    all_fields = OrderQuantity.objects.all()
    all_fields = (
            all_fields.annotate(cost_position=F('quantity') * F('product__price')).all()
        )
    orders_with_cost = all_fields.values('order').annotate(
                cost_order=Sum('cost_position')
                ).values('order',
                         'cost_order')

    for order in orders_with_cost:
        need_order = Order.objects.get(id=order['order'])
        need_order.cost = order['cost_order']
        need_order.save()

def move_backward(apps, schema_editor):
    OrderQuantity = apps.get_model('foodcartapp', 'OrderQuantity')
    Order = apps.get_model('foodcartapp', 'Order')
    all_fields = OrderQuantity.objects.all()
    all_fields = (
            all_fields.annotate(cost_position=F('quantity') * F('product__price')).all()
        )
    orders_with_cost = all_fields.values('order').annotate(
                cost_order=Sum('cost_position')
                ).values('order',
                         'cost_order')

    for order in orders_with_cost:
        need_order = Order.objects.get(id=order['order'])
        need_order.cost = order['cost_order']
        need_order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderquantity_price'),
    ]

    operations = [
         migrations.RunPython(copy_cost_orders,
                              move_backward)
    ]

