# Generated by Django 3.2.12 on 2022-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20220613_1751'),
        ('foodcartapp', '0047_auto_20220613_1757'),
    ]

    operations = [
    ]
