# Generated by Django 3.2.12 on 2022-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_merge_0046_auto_20220613_1751_0047_auto_20220613_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('N', 'Необработанный'), ('Y', 'Обработан')], default='N', max_length=2),
        ),
    ]
