# Generated by Django 3.2.12 on 2022-06-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20220614_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
