# Generated by Django 3.2.12 on 2022-06-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронно')], default='С', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
