# Generated by Django 3.2.12 on 2022-06-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurantmenuitem'),
        ),
    ]
