# Generated by Django 3.2.12 on 2022-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_rename_longtitude_coordinateaddress_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронно')], max_length=2, verbose_name='способ оплаты'),
        ),
    ]
