# Generated by Django 3.2.12 on 2022-06-18 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_alter_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество'),
        ),
    ]
