# Generated by Django 3.2.12 on 2022-06-18 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0065_alter_orderquantity_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderquantity',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество'),
            preserve_default=False,
        ),
    ]
