# Generated by Django 3.2.12 on 2022-06-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0066_auto_20220618_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderquantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_order_quantity', to='foodcartapp.order'),
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_order_quantity', to='foodcartapp.product', verbose_name='товар'),
        ),
    ]
