# Generated by Django 3.2.12 on 2022-06-18 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0067_auto_20220618_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderquantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
        ),
    ]
