# Generated by Django 3.2.12 on 2022-06-26 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0073_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderquantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
