# Generated by Django 3.2.12 on 2022-06-26 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0074_alter_orderquantity_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinateaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='coordinateaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='долгота'),
        ),
    ]
