# Generated by Django 3.2.12 on 2022-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0075_auto_20220626_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinateaddress',
            name='address',
            field=models.CharField(max_length=150, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='адрес'),
        ),
    ]
